name: frontend ci

"on":
  push:
    branches:
      - master
  pull_request:

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: set up node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: install dependencies
        run: |
          npm install

      - name: build frontend
        run: |
          npm run build
